stages: [build, deploy]

build:
  image: node:14-alpine
  stage: build
  script:
    - apk update && \
        apk upgrade && \
        apk add --no-cache \
        alpine-sdk git python \
        build-base libtool autoconf \
        automake gzip g++ \
        make tzdata \
        && cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime \
        && echo "Asia/Bangkok" > /etc/timezone
    - npm i
    - npm run build:dist
  only:
    - master

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
